language: c

git:
  depth: 1

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=Debug
    - os: linux
      env: BUILD_TYPE=Release
    - os: osx
      env: BUILD_TYPE=Debug
    - os: osx
      env: BUILD_TYPE=Release
    - os: windows
      env: BUILD_TYPE=Debug
      before_install: choco install cmake
    - os: windows
      env: BUILD_TYPE=Release
      before_install: choco install cmake

install:
  - cmake . -Bbuild -DCMAKE_INSTALL_PREFIX=build -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build ./build
